version: "3"
services:
  youdeyiwu:
    labels:
      - maintainer=dafengzhen
      - description=Build youdeyiwu backend application
    container_name: youdeyiwu
    image: "youdeyiwu:${TAG}"
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DATABASE_ENDPOINT}/${DATABASE_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC&allowMultiQueries=true
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    build:
      context: .
    networks:
      - server
    volumes:
      - logs:/youdeyiwu/logs
    restart: on-failure
    ports:
      - "8080:8080"

networks:
  default:
    name: youdeyiwu_default
  server:
    name: youdeyiwu_server

volumes:
  logs:
